language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - "sh start_server.sh &"
  - docker-compose run app sh -c "python manage.py test && flake8"
