language: python
python:
    - "3.6"

services:
    - docker

install:
    - pipenv install

before_script: pip install docker-compose

script:
    - docker-compose run app sh -c "python manage.py test && flake8"
